name: Richard CI/CD to EC2
on:
  push:
    branches: [ "main" ]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      
      - name: Upload app to EC2
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          source: "app/*"
          target: "/home/ubuntu/richard-app-release/"
      
      - name: Deploy and restart service
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            set -euxo pipefail
            
            # Stop the service
            sudo systemctl stop richard-app
            
            # Remove old app files
            sudo rm -rf /opt/richard-app/app.py /opt/richard-app/templates
            
            # Copy new files to the correct location
            sudo cp /home/ubuntu/richard-app-release/app/app.py /opt/richard-app/app.py
            sudo cp -r /home/ubuntu/richard-app-release/app/templates /opt/richard-app/templates
            
            # Install requirements if they exist
            if [ -f /home/ubuntu/richard-app-release/app/requirements.txt ]; then
              sudo pip3 install -r /home/ubuntu/richard-app-release/app/requirements.txt
            fi
            
            # Fix permissions
            sudo chown -R ubuntu:ubuntu /opt/richard-app
            
            # Start the service
            sudo systemctl start richard-app
            sleep 3
            sudo systemctl status --no-pager richard-app