name: Deploy to EC2 (Richard)

on:
  push:
    branches: ["main"]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Sanity check secrets
        run: |
          test -n "${{ secrets.EC2_SSH_KEY }}" && echo "SSH key present" || (echo "EC2_SSH_KEY missing" && exit 1)
          test -n "${{ secrets.EC2_HOST }}" && echo "Host present" || (echo "EC2_HOST missing" && exit 1)
          test -n "${{ secrets.EC2_USER }}" && echo "User present" || (echo "EC2_USER missing" && exit 1)

      - name: Upload files to EC2
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          source: "app/**"
          target: "/opt/richard-app"

      - name: Install deps & restart
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            set -e
            cd /opt/richard-app
            ls -la
            if [ -f requirements.txt ]; then sudo pip3 install -r requirements.txt; fi
            sudo systemctl restart richard-app
            sudo systemctl status --no-pager richard-app || true
